import {
  twitter,
  instagram,
  telegram,
  facebook,
  youtube,
  house_icon,
  clock_icon,
  SLIoT2023_1,
  SLIoT2023_2,
  SLIoT2023_3,
  SLIoT2023_4,
  SLIoT2023_5,
  SLIoT2023_6,
  SLIoT2023_7,
  SLIoT2023_8,
  SLIoT2023_9,
  SLIoT2023_10,
  sliot2022_1,
  sliot2022_2,
  sliot2022_3,
  sliot2022_4,
  sliot2022_5,
  sliot2022_6,
  sliot2022_7,
  sliot2022_8,
  sliot2022_9,
  sliot2022_10,
  sliot2022_11,
  sliot2019_1,
  sliot2019_2,
  sliot2019_3,
  sliot2019_4,
  sliot2019_5,
  sliot2019_6,
  sliot2019_7,
  sliot2019_8,
  sliot2019_9,
  sliot2019_10,
  sliot2019_11,
  uom,
  cse,
  iesl,
  sltLogo,
  chairman,
  viceChairman,
} from "../assets";

export const navigation = [
  {
    id: "1",
    title: "Home",
    url: "home",
  },
  {
    id: "2",
    title: "About",
    url: "about",
  },
  {
    id: "3",
    title: "Categories",
    url: "categories",
  },
  {
    id: "4",
    title: "Challenge",
    url: "challenge",
  },
   {
    id: "5",
    title: "Timeline",
    url: "timeline",
   },
  {
    id: "6",
    title: "Gallery",
    url: "gallery",
  },
  {
    id: "7",
    title: "Spotlight",
    url: "spotlight",
  },
  {
    id: "8",
    title: "Partners",
    url: "partners",
  },
  {
    id: "9",
    title: "Contact",
    url: "contact",
    onlyMobile: true,
  },
];

export const socials = [
  // {
  //   id: "0",
  //   title: "Twitter",
  //   iconUrl: twitter,
  //   url: "#",
  // },
  {
    id: "1",
    title: "YouTube",
    iconUrl: youtube,
    url: "https://www.youtube.com/@SLIOT-Challenge",
  },
  {
    id: "2",
    title: "Facebook",
    iconUrl: facebook,
    url: "https://web.facebook.com/srilankaIoTchallenge",
  },
];

export const aboutGridItems = [
  {
    id: 1,
    title: "What is the SLIoT Challenge?",

    description: `The SLIoT Challenge is an annual IoT competition organized by the Department of Computer Science & Engineering, University of Moratuwa, in collaboration with SLT-MOBITEL and The Institution of Engineers Sri Lanka (IESL). The goal of this competition is to raise awareness about the "Internet of Things" (IoT) and encourage its usage among Sri Lankans. The organizers aim to evaluate IoT-based solutions developed to meet industrial-level standards, addressing major local and global issues. We aspire to ignite imagination and creativity by providing a competitive platform for talented and curious participants. Ideas will be evaluated based on creativity, value, benefits, and technologies used. Winners will be selected from the best ideas and performance on the event day. The competition will be held in three categories: - School Category - Undergraduate Category - Open Category.`,

    className:
      "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh] text-n-1",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
  },
  {
    id: 2,
    title: "Where",
    description: "Final competition will be held at University of Moratuwa",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2 text-n-1",
    imgClassName: "mt-5 ml-5 h-20 w-20",
    titleClassName: "justify-end items-end text-end",
    img: house_icon,
    spareImg: "",
  },
  {
    id: 3,
    title: "When",
    description: `To be decided <br> Check the Timeline for more details `,
    className: "lg:col-span-2 md:col-span-3 md:row-span-2 text-n-1",
    imgClassName: "mt-5 ml-5 h-20 w-20",
    titleClassName: "justify-end items-end text-end",
    img: clock_icon,
    spareImg: "",
  },
];

export const previousSLIoTShowcases = [
  {
    id: 8,
    title: "SLIoT 2023",
    description: "",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[40vh]",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-end items-end text-end",
    img: SLIoT2023_1,
    spareImg: "",
    link: "",
    imageArray: [
      SLIoT2023_1,
      SLIoT2023_2,
      SLIoT2023_3,
      SLIoT2023_4,
      SLIoT2023_5,
      SLIoT2023_6,
      SLIoT2023_7,
      SLIoT2023_8,
      SLIoT2023_9,
      SLIoT2023_10,
    ],
    overlayClassName: "bg-black bg-opacity-20",
  },
  {
    id: 9,
    title: "SLIoT 2022",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-end items-end text-end",
    img: sliot2022_1,
    spareImg: "",
    link: "",
    imageArray: [
      sliot2022_1,
      sliot2022_2,
      sliot2022_3,
      sliot2022_4,
      sliot2022_5,
      sliot2022_6,
      sliot2022_7,
      sliot2022_8,
      sliot2022_9,
      sliot2022_10,
      sliot2022_11,
    ],
    overlayClassName: "bg-black bg-opacity-20",
  },
  {
    id: 10,
    title: "SLIoT 2020",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-end items-end text-end",
    img: "https://img.youtube.com/vi/HLMQvP5e98c/hqdefault.jpg",
    spareImg: "",
    link: "https://www.youtube.com/embed/HLMQvP5e98c",
    overlayClassName: "bg-black bg-opacity-20",
  },
  {
    id: 11,
    title: "SLIoT 2019",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-end items-end text-end",
    img: sliot2019_1,
    spareImg: "",
    link: "",
    imageArray: [
      sliot2019_1,
      sliot2019_2,
      sliot2019_3,
      sliot2019_4,
      sliot2019_5,
      sliot2019_6,
      sliot2019_7,
      sliot2019_8,
      sliot2019_9,
      sliot2019_10,
      sliot2019_11,
    ],
    overlayClassName: "bg-black bg-opacity-20",
  },
  {
    id: 12,
    title: "SLIoT 2018",
    description: "",
    className: "md:col-span-3 md:row-span-2",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-end items-end text-end",
    img: "https://img.youtube.com/vi/9bpgGZMNd28/hqdefault.jpg",
    spareImg: "",
    link: "https://www.youtube.com/embed/9bpgGZMNd28",
    overlayClassName: "bg-black bg-opacity-20",
  },
  {
    id: 13,
    title: "SLIoT 2017",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-end items-end text-end",
    img: "https://img.youtube.com/vi/v6wOjQGANsE/hqdefault.jpg",
    spareImg: "",
    link: "https://www.youtube.com/embed/v6wOjQGANsE",
    overlayClassName: "bg-black bg-opacity-20",
  },
];

export const currentSLIoTShowcases = [
  {
    id: 14,
    title: "Open & Uni Workshop",
    description: "Coming Soon",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
    imageArray: [],
    overlayClassName: "",
  },
  {
    id: 15,
    title: "School Workshop",
    description: "Coming Soon",
    className: "md:col-span-3 md:row-span-2",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
    imageArray: [],
    overlayClassName: "",
  },
  {
    id: 16,
    title: "Open & Uni Semi Finals",
    description: "Coming Soon",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
    imageArray: [],
    overlayClassName: "",
  },
  {
    id: 17,
    title: "School Semi Finals",
    description: "Coming Soon",
    className: "lg:col-span-3 md:col-span-3 md:row-span-1",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
    imageArray: [],
    overlayClassName: "",
  },
  {
    id: 18,
    title: "Grand Finale",
    description: "Coming Soon",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    imgClassName: "w-full h-full object-cover",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
    imageArray: [],
    overlayClassName: "",
  },
];

export const spotlight = [
  {
    id: 1,
    title: "What is IoT?",
    des: "Explained by Prof. Chandana Gamage | SLIoT Challenge 2025",
    des2: "SLIoT Challenge 2025",
    img: "/p1.svg",
    link: "https://www.youtube.com/embed/mIJdCAKL71I",
  },
  // {
  //   id: 2,
  //   title: "What is Industry 4.0?",
  //   des: "Explained by Prof. Chandana Gamage | SLIoT Challenge 2025",
  //   img: "/p2.svg",
  //   link: "https://www.youtube.com/embed/kdI_04VvLmk",
  // },
  {
    id: 3,
    title: "How to start an IoT Project?",
    des: "Explained by Dr. Kutila Gunasekara | SLIoT Challenge 2025",
    des2: "SLIoT Challenge 2025",
    img: "/p3.svg",
    link: "https://www.youtube.com/embed/vVw2Q92ydsc",
  },
  {
    id: 4,
    title: "Communication between Embedded Devices",
    des: "Explained by Dr. Sulochana Sooriyaarachchi | SLIoT Challenge 2025",
    des2: "SLIoT Challenge 2025",
    img: "/p4.svg",
    link: "https://www.youtube.com/embed/eiyhMLFVdMU",
  },
  {
    id: 5,
    title: "Value of Security for IoT Solutions",
    des: "Explained by Dr. Sunimal Rathnayaka | SLIoT Challenge 2025",
    des2: "SLIoT Challenge 2025",
    img: "/p1.svg",
    link: "https://www.youtube.com/embed/Gw6NmLdHqiA",
  },
  {
    id: 6,
    title: "Applications of IoT",
    des: "Explained by Prof. Chandana Gamage | SLIoT Challenge 2025",
    des2: "SLIoT Challenge 2025",
    img: "/p2.svg",
    link: "https://www.youtube.com/embed/LJnJDyBk4_4",
  },
  {
    id: 7,
    title: "IOT Sensors",
    des: "Explained by Dr. Chathuranga Hettiarachchi | SLIoT Challenge 2025",
    des2: "SLIoT Challenge 2025",
    img: "/p3.svg",
    link: "https://www.youtube.com/embed/MHwnCB3-kzA",
  },
  {
    id: 8,
    title: "What is AIOT?",
    des: "Explained By Dr. Thanuja Ambegoda | SLIoT Challenge 2025",
    des2: "SLIoT Challenge 2025",
    img: "/p4.svg",
    link: "https://www.youtube.com/embed/UVdn4ZTJ3_Q",
  },
];

export const categories = [
  {
    id: 1,
    title: "SCHOOL CATEGORY",
    category: "school",
  },
  {
    id: 2,
    title: "UNIVERSITY CATEGORY",
    category: "university",
  },
  {
    id: 3,
    title: "OPEN CATEGORY",
    category: "open",
  },
  // {
  //   id: 4,
  //   title: "Lead Frontend Developer",
  //   desc: "Developed and maintained user-facing features using modern frontend technologies.",
  //   className: "md:col-span-2",
  //   thumbnail: "/exp4.svg",
  // },
];

export const organizers = [
  {
    id: 1,
    img: iesl,
    className: "w-36",
  },
  {
    id: 2,
    img: cse,
    className: "w-36",
  },
  {
    id: 3,
    img: sltLogo,
    className: "w-36",
  },
  {
    id: 4,
    img: uom,
    className: "w-36",
  },
]; 

export const contact = [
  {
    id: 1,
    img: chairman,
    name: "Pavan Epa",
    position: "Event Chairman",
    link: "mailto:pavan.22@cse.mrt.ac.lk",
    mail: "pavan.22@cse.mrt.ac.lk",
  },
  {
    id: 2,
    img: viceChairman,
    name: "Kaveesha Kapuruge",
    position: "Event Vice Chairman",
    link: "mailto:kaveesha.22@cse.mrt.ac.lk",
    mail: "kaveesha.22@cse.mrt.ac.lk",
  },
];
